[package]
name = "chronical"
version = "0.1.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.42"
chrono-tz = "0.10.4"
napi = "3.7.1"
napi-derive = "3.4.1"
rrule = "0.14.0"
thiserror = "2.0.17"

[build-dependencies]
napi-build = "2.3.1"
